server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices
spring.datasource.username=postgres
spring.datasource.password=Test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:ThisIsA64CharacterSecretKeyForHS512Algorithm1234567890AbCdEfGhIjKlMnOpQrStUvWxYa!!}
jwt.expiration-ms=10800000
jwt.access-token-expiration-ms=10800000

# Default Circuit Breaker Config
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s

# Circuit Breaker Instances
resilience4j.circuitbreaker.instances.orderService.baseConfig=default
resilience4j.circuitbreaker.instances.authService.baseConfig=default
resilience4j.circuitbreaker.instances.productService.baseConfig=default


